name: Auto Deploy master to Production

on:
  workflow_dispatch:

jobs:
  search_and_validate_mr:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.mr_number.outputs.mr_number }}
    steps:
      # - name: Set timezone to Eastern
      #   uses: szenius/set-timezone@v1.0
      #   with:
      #     timezoneLinux: "America/New_York"
      - name: Commit new snapshots and push
        run: |
          pwd
          date '+%Y/%M/%d %H:%m ET'
          printenv
