name: Auto Deploy master to Production

on:
  workflow_dispatch:

jobs:
  search_and_validate_mr:
    runs-on: ubuntu-latest
    outputs:
      time_string: ${{ steps.get_time_string.outputs.time_string }}
    steps:
      - name: Set timezone to Eastern
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'America/New_York'
      # - name: Debugging info
      #   run: |
      #     date '+%Y/%m/%d %H:%M ET'
      - id: get_time_string
        name: Get time string for MR search
        run: |
          date '+%Y/%m/%d %H:%M ET' > ./time
          TIME_STRING=`cat ./time`
          rm ./time
          echo $TIME_STRING
          echo "::set-output name=time_string::$TIME_STRING"
      - name: Grab matching deploy MR
        run: |
          echo $TIME_STRING
          echo ${{ steps.get_time_string.outputs.time_string }}
          TIME_STRING=`echo ${{steps.get_time_string.outputs.time_string}}`
          echo $TIME_STRING
          echo ${{secrets.GITHUB_TOKEN}} | gh auth login --with-token
          # gh issue list \
          #   -R 'gileswells/developer-portal' \
          #   -l 'repo: developer-portal' \
          #   --limit 1 \
          #   --json id,number,state,labels,title \
          #   --jq "[.[]|select(.title==\"Deploy developer-portal to production ($TIME_STRING)\")][0]" \
          #   > issue.json
          # cat issue.json
          TIME_STRING='2022/02/07 09:00 ET'
          gh issue list \
            -R 'gileswells/developer-portal' \
            -l 'repo: developer-portal' \
            --limit 1 \
            --json id,number,state,labels,title \
            --jq "[.[]|select(.title==\"Deploy developer-portal to production ($TIME_STRING)\")][0]" \
            > issue.json
          cat issue.json
          jq ".labels" issue.json | jq -e ".[] | select(.name==\"status: approved\")"
