name: Pull Request Labels
on:
  pull_request:
    branches: [master, shutdown-master]
    types: [opened, labeled, unlabeled, synchronize, reopened, ready_for_review]
  workflow_run:
    workflows: ['Automatically label PRs with content changes']
    types:
      - completed

jobs:
  is_labeled:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: |
            impact: users
            impact: maintainers
      - uses: mheap/github-action-required-labels@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 0
          labels: 'DO NOT MERGE'
