name: Test self-cancel on failure

on:
  workflow_dispatch:

jobs:
  cancel_yourself:
    runs-on: ubuntu-latest
    steps:
      - id: step_with_error
        name: This step will exit 1
        continue-on-error: true
        run: |
          echo "This step should end with a failure";
          exit 1;
      - name: Self cancel the job on failure
        if: steps.step_with_error.outcome == 'failure'
        run: |
          echo ${{github.run_id}}
          echo ${{secrets.GIT_AUTO_DEPLOY_TOKEN}} | gh auth login --with-token
          gh run cancel ${{github.run_id}}
          sleep 60
      - name: This shouldn't fire
        run: echo "Why are you here? Go home. The movie's over."
