name: Node.js Unit Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: action/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run test:unit:ci
